# Generated by Django 6.0.1 on 2026-01-22 09:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, default='fa-spa', max_length=50, verbose_name='Ícone (FontAwesome)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionário'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Tipo de Utilizador')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('morada', models.TextField(blank=True, null=True, verbose_name='Morada')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nif', models.CharField(blank=True, max_length=9, null=True, verbose_name='NIF')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='utilizadores/', verbose_name='Foto de Perfil')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'ordering': ['-data_criacao'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('preparacao', 'Em Preparação'), ('pronta', 'Pronta para Levantamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (€)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FeriasFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo': 'funcionario'}, on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Férias/Indisponibilidade',
                'verbose_name_plural': 'Férias/Indisponibilidades',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço (€)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponível')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='app.categoriaproduto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.encomenda', verbose_name='Encomenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Encomenda',
                'verbose_name_plural': 'Itens de Encomenda',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('duracao', models.PositiveIntegerField(help_text='Duração do serviço em minutos (15-480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='Duração (minutos)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço (€)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='Imagem')),
                ('capacidade_maxima', models.PositiveIntegerField(default=1, help_text='Número máximo de clientes por sessão', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade Máxima')),
                ('requer_prescricao', models.BooleanField(default=False, verbose_name='Requer Prescrição Médica')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='app.categoriaservico', verbose_name='Categoria')),
                ('funcionarios', models.ManyToManyField(blank=True, limit_choices_to={'tipo': 'funcionario'}, related_name='servicos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Funcionários Atribuídos')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída'), ('nao_compareceu', 'Não Compareceu')], default='pendente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas (Staff)')),
                ('preco_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Final')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'funcionario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo': 'funcionario'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Horário de Funcionário',
                'verbose_name_plural': 'Horários de Funcionários',
                'ordering': ['funcionario', 'dia_semana', 'hora_inicio'],
                'unique_together': {('funcionario', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
