# Generated by Django 5.1.7 on 2026-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='estado_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhado', 'Falhado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20, verbose_name='Estado de Pagamento'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='faturacao_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Faturação'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='faturacao_morada',
            field=models.TextField(blank=True, verbose_name='Morada de Faturação'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='faturacao_nif',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='faturacao_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome de Faturação'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('simulado', 'Pagamento Simulado'), ('rececao', 'Pagamento na Receção')], default='simulado', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='numero_fatura',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número da Fatura'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='referencia_pagamento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referência de Pagamento'),
        ),
    ]
