# Generated by Django 5.1.7 on 2026-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_encomenda_data_pagamento_encomenda_estado_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='entrega_morada',
            field=models.TextField(blank=True, verbose_name='Morada de Entrega'),
        ),
    ]
