# Generated by Django 5.1.7 on 2026-05-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_encomenda_entrega_morada'),
    ]

    operations = [
    ]
