# Generated by Django 4.2.30 on 2026-05-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_recepcao_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriasfuncionario',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='horariofuncionario',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('preparacao', 'Em Preparação'), ('enviada', 'Enviada'), ('pronta', 'Pronta para Levantamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='feriasfuncionario',
            name='funcionario',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['funcionario', 'recepcao']}, on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='horariofuncionario',
            name='funcionario',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['funcionario', 'recepcao']}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('recepcao', 'Receção'), ('funcionario', 'Funcionário'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Tipo de Utilizador'),
        ),
    ]
