# Generated by Django 4.2.30 on 2026-06-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feriasfuncionario_estado_horariofuncionario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaservico',
            name='icone',
            field=models.CharField(blank=True, default='fa-layer-group', max_length=50, verbose_name='Ícone (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='requer_prescricao',
            field=models.BooleanField(default=False, verbose_name='Requer Validação Prévia'),
        ),
        migrations.CreateModel(
            name='BloqueioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora Fim')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['funcionario', 'recepcao']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='app.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Bloqueio de Horário',
                'verbose_name_plural': 'Bloqueios de Horários',
                'ordering': ['-data', 'hora_inicio'],
            },
        ),
    ]
