# Generated by Django 4.2.30 on 2026-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_categoriaservico_icone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='is_aula',
            field=models.BooleanField(default=False, help_text='Marcar se este serviço é uma aula (horários fixos ou reservas ad-hoc)', verbose_name='Aula'),
        ),
    ]
