# Generated by Django 4.2.30 on 2026-06-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_servico_is_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariofuncionario',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim (opcional)'),
        ),
        migrations.AddField(
            model_name='horariofuncionario',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início (opcional)'),
        ),
    ]
