# Generated by Django 4.2.30 on 2026-06-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_horariofuncionario_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariofuncionario',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_servico', to='app.servico', verbose_name='Serviço'),
        ),
    ]
