# Generated by Django 4.2.30 on 2026-06-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_horariofuncionario_servico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariofuncionario',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='horariofuncionario',
            constraint=models.UniqueConstraint(condition=models.Q(('servico__isnull', True)), fields=('funcionario', 'dia_semana', 'hora_inicio'), name='uniq_horario_global_funcionario_dia_hora'),
        ),
        migrations.AddConstraint(
            model_name='horariofuncionario',
            constraint=models.UniqueConstraint(condition=models.Q(('servico__isnull', False)), fields=('servico', 'funcionario', 'dia_semana', 'hora_inicio'), name='uniq_horario_servico_funcionario_dia_hora'),
        ),
    ]
